/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLKS.Views;

import QLKS.Dao.KhoaPhongController;
import QLKS.Models.Phong;
import java.util.ArrayList;
import java.sql.SQLException;
import QLKS.Models.NhanVien;
import QLKS.Helper.DatabaseHelper;
import QLKS.Models.CustomtableKhoaphong;
import com.sun.source.tree.BreakTree;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MinhQuan
 */
public class KhoaPhong extends javax.swing.JPanel {

    /**
     * Creates new form KhoaPhong
     */
     static KhoaPhongController kpcontroller= new KhoaPhongController();
    ArrayList<Phong> list= new ArrayList<>();
    int selectRow=-1;
    public KhoaPhong()throws SQLException{
        initComponents();
        load();
    }
    
     void load() throws SQLException{
        list = kpcontroller.getAllPhong();
        tblPhong.setModel(new CustomtableKhoaphong(list) ); 
    }
      private void ClearTxt(){
        txtMaPhong.setText("");
        txtGiaPhong.setText("");
        
        txtMaPhong.getAction();
        cbxLoaiPhong.setSelectedIndex(0);  
        rbtnKhoa.setSelected(false);
        rbtnMo.setSelected(false);

      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtGiaPhong = new javax.swing.JTextField();
        btnCapnhat = new javax.swing.JButton();
        rbtnKhoa = new javax.swing.JRadioButton();
        rbtnMo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        cbxLoaiPhong = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("KHÓA PHÒNG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã phòng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Loại phòng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Giá Phòng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tình Trạng");

        btnCapnhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKS/icons/khoa_phong.png"))); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnKhoa);
        rbtnKhoa.setText("Khóa");

        buttonGroup1.add(rbtnMo);
        rbtnMo.setText("Mở");

        tblPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhong);

        cbxLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường đơn", "Vip đơn" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnMo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtGiaPhong)
                                    .addComponent(txtMaPhong)
                                    .addComponent(cbxLoaiPhong, 0, 260, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCapnhat)
                                .addGap(192, 192, 192)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnKhoa)
                    .addComponent(rbtnMo))
                .addGap(18, 18, 18)
                .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
                 
              
            try {
                   String tam="";
        if(rbtnKhoa.isSelected())
        {
            tam="Đang bảo trì";
        }
        else if(rbtnMo.isSelected())
        {
            tam="Còn trống";
        }
                String MaPhong=txtMaPhong.getText();
                String LoaiPhong=cbxLoaiPhong.getSelectedItem().toString();
                Float GiaPhong=Float.parseFloat(txtGiaPhong.getText());
                String TinhTrang = tam;
                Phong kp= new Phong( MaPhong, LoaiPhong, GiaPhong, TinhTrang);
                list.set(selectRow,kp);
                
              
             
                try {
                    if(kpcontroller.updateKhoaPhong(kp)){
                        JOptionPane.showMessageDialog(null, "Cập nhật tình trạng phòng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        ClearTxt();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(KhoaPhong.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                    } catch (Exception ex) {
                System.out.print(ex);
                
            }
            try {
                load();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void tblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMouseClicked
        // TODO add your handling code here:
        selectRow=tblPhong.getSelectedRow();
        int i=0;
        for(Phong phong:list){
            if(phong.getMaPhong().equals(tblPhong.getValueAt(selectRow,0))){
            i=list.indexOf(phong);
        }
        }
        Phong a=list.get(i);
        txtMaPhong.setText(a.getMaPhong());
        if(a.getLoaiPhong().equals("Thường đơn")){
          cbxLoaiPhong.setSelectedItem("Thường đơn");
      }else {
          cbxLoaiPhong.setSelectedItem("Vip đơn");
      }
        txtGiaPhong.setText(""+a.getGiaPhong());
        if(a.getTinhTrang().equals("Còn trống"))
        {
            rbtnMo.setSelected(true);
        }
        else if(a.getTinhTrang().equals("Đang sử dụng")){
            JOptionPane.showMessageDialog(this, "Phòng đang được sử dụng. \n  Không được thay đổi tình trạng");
            ClearTxt();
        }
        else {
            rbtnKhoa.setSelected(true);
        }
    }//GEN-LAST:event_tblPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbtnKhoa;
    private javax.swing.JRadioButton rbtnMo;
    private javax.swing.JTable tblPhong;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaPhong;
    // End of variables declaration//GEN-END:variables
}
